[build-system]
requires = ['setuptools', 'wheel']
build-backend = "setuptools.build_meta"

[project]
name='pyutplugins'
dynamic     = ["version"]
description = 'Pyut Plugins'
readme      = "README.md"
license     = {text = 'GNU AFFERO GENERAL PUBLIC LICENSE'}
authors     = [{name = 'Humberto A. Sanchez II', email = 'Humbert.A.Sanchez.II@gmail.com'}]
maintainers = [{name = 'Humberto A. Sanchez II', email = 'Humbert.A.Sanchez.II@gmail.com'}]
keywords    = ['pyut', 'python', 'plugin']

dependencies = [
'pyutmodelv2==2.0.0a6',
                      'ogl==2.0.0a7',
                      'untanglepyut==2.0.0a7',
                      'oglio==2.0.0a7',
                      'codeallybasic~=0.5.2',
                      'codeallyadvanced~=0.5.2',
                      'pyumldiagrams==3.1.0',
                      'wxPython~=4.2.1',
                      'antlr4-python3-runtime==4.11.1',
                      'networkx==3.0',
                      'orthogonal==1.2.0',]
[project.urls]
Repository = 'https://github.com/hasii2011/pyutplugins'


[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools.package-data]
pyutplugins = ['py.typed']


[tool.setuptools.dynamic]
version = {attr = 'pyutplugins.__version__'}
