[tool.poetry]
name = "sdwis_drink_water"
version = "1.1.0"
description = "Python wrappers for the Envirofacts Data Service API provided by the U.S. Environmental Protection Agency (EPA), with a focus on the Safe Drinking Water Information System (SDWIS)."
authors = ["norahtao"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.12.2"
pandas = "^2.1.4"
requests = "^2.31.0"
requests-cache = "^1.1.1"
tabulate = "^0.9.0"
tqdm = "^4.66.1"
setuptools = "^69.0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
myst-nb = "^1.0.0"
sphinx-autoapi = "^3.0.0"
sphinx-rtd-theme = "^2.0.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
