[tool.poetry]
name = "pypi-eg-alebg"
version = "0.1.1"
description = "Example project to test publishing to PyPI"
authors = ["Luis Alejandro Bordo Garc√≠a <bgluiszz@gmail.com>"]
readme = "README.md"
license = "Custom"  # This is the line you're adding

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
