[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SnoSample"
version = "1.0.0"
authors = [
  { name="Max Snoodijk"},
]
description = "Template and tools for Python projects."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
]

[tool.setuptools]
packages = ["snosample"]
package-dir = {"snosample" = "src"}
