[tool.poetry]
name = "langsnapy"
version = "0.0.2"
description = "Snapshot your LLMs, NLP and Chatbots"
authors = ["Mykhailo Chalyi <mike@chaliy.name>"]
readme = "README.md"

packages = [
    { include = "langsnapy", from = "." },
]

[tool.poetry.dependencies]
python = "^3.11"
dataclasses-json = "^0.6.3"
pyyaml = "^6.0.1"
markdown-it-py = {version = "^3.0.0", optional = true}


[tool.poetry.extras]
runtime-deps = ["markdown-it-py"]

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.8"
pytest = "^7.4.3"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
