[tool.poetry]
name = "chainalysis-sanction-verifier"
version = "0.1.2"
description = ""
authors = ["Matt Johnstone <johnstone.mattjames@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
httpx = ">=0.23.0"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
python-dotenv = "^1.0.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
