[tool.poetry]
name = "glob-utils"
version = "0.0.3"
description = ""
authors = ["Oscar Bahamonde <o.bahamonde@globant.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.25.2"
rich = "^13.7.0"
tenacity = "^8.2.3"
pydantic = "1.10.12"
fastapi = "^0.105.0"
sse-starlette = "^1.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
