[tool.poetry]
name = "novum_api_client"
version = "0.6.0"
description = "This library contains the basic api functions for Novum Service Center."
authors = ["Leonardo <l.biz@novum-engineering.com>"]
long_description_content_type = "text/markdown"
include = ["README.md", "CHANGELOG.md"]


[tool.poetry.metadata]
description = "This library contains the basic api functions for Novum Service Center."
long_description = "file: README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
