[tool.poetry]
name = "hacku"
version = "1.6.0"
description = "hack u"
authors = ["0day <just@hacku.orz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras = ["socks"], version = "^0.25.2"}
beautifulsoup4 = "^4.12.2"
loguru = "^0.7.2"
id-validator = "^1.0.20"
random-user-agent = "^1.0.1"
jieba = "^0.42.1"
pycryptodome = "^3.19.0"
rsa = "^4.9"
pyexecjs = "^1.5.1"
shodan = "^1.30.1"
ujson = "^5.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
