[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "housemate"
version = "2.0"
authors = [
  { name="Andrew Sarracini", email="andrewsarracini1@gmail.com" },
  { name="Craig Adlam", email="cadlam87@gmail.com"}
]
description = "HouseMate shows users different properties to rent or purchase based on their specific needs." 
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/CraigAdlam/housemate"

[tool.poetry.scripts]
housemate_main = "housemate.housemate_main:main"