[tool.poetry]
name = "python_hindi"
version = "0.1.0"
description = "Python in Hindi"
authors = ["Karan Singh <itsrealkaran@outlook.com>"]
license = "BSD-4-Clause"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
homepage = "https://github.com/itsrealkaran/python-hindi"

[tool.poetry.dependencies]
python = "^3.6"
ideas = "^0.0.22"
rich = "^13.7.0"

[tool.poetry.extras]
errors = ["friendly", "friendly-traceback"]

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pyhi = 'python_hindi.__main__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
issues = "https://github.com/itsrealkaran/python-hindi/issues"
