[build-system]
build-backend = "pdm.backend"
requires = [
    "pdm-backend",
]

[project]
authors = [
    { email = "louismmx@gmail.com", name = "Louis Maddox" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Pydantic :: 2",
    "Framework :: Pydantic",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "defopt",
    "pydantic>=2.4.2",
    "GitPython>=3.1.40",
]
description = "Git diff parser."
dynamic = []
keywords = [
    "git",
    "pydantic",
    "pypi",
]
name = "fugit"
readme = "README.md"
requires-python = ">=3.10,<3.12"
version = "0.0.3"

[project.license]
text = "MIT"

[project.scripts]
fugit = "fugit.cli:run_cli"

[project.urls]
Homepage = "https://github.com/lmmx/fugit"
Repository = "https://github.com/lmmx/fugit.git"

[tool.isort]
known_first_party = [
    "fugit",
]

[tool.pdm.version]
path = "src/fugit/__init__.py"
source = "file"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.0",
]
develop = [
    "pysnooper>=1.2.0",
]
mkdocs = []
docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material[recommended,imaging]>=9.5.2",
    "mkdocstrings>=0.24.0",
]

[tool.ruff]
ignore = [
    "C408",
    "C901",
    "E501",
    "E741",
]
ignore-init-module-imports = true
select = [
    "C",
    "E",
    "F",
    "I",
    "W",
]

[tool.ruff.isort]
lines-after-imports = 2

[tool.ruff.lint.isort]
known-first-party = [
    "fugit",
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "E401",
]

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
