[build-system]
requires = [
    "setuptools>=61.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "fileunity"
version = "1.3.1"
description = "easy data objects to load and save"
readme = "README.rst"
authors = [
    { name = "Johannes", email = "johannes-programming@posteo.org" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []
dependencies = [
    "pandas>=2.1.2",
    "simple_tsv>=1.0",
    "tomli_w>=1.0",
]
requires-python = ">=3.11"

[project.license]
file = "LICENSE.txt"

[project.urls]
Source = "https://github.com/johannes-programming/fileunity"
Download = "https://pypi.org/project/fileunity/#files"
