[tool.poetry]
name = "foodreversefda"
version = "0.1.0"
description = "Basic functionality. Enter event_id and retrieve event directory."
authors = ["Yifei Chen <yc4307@columbia.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
vcrpy = "^5.1.0"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
