[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "datacentertracesdatasets-cli"
version = "1.0"
authors = [
    { name = "Alejandro Fernández-Montes", email = "afdez@us.es" },
    { name = "Damián Fernández-Cerero", email = "damiancerero@us.es" }
]
dependencies = ["datacentertracesdatasets", "pandas"]
description = "Datacentertracesdatasets-cli is an open-source tool designed to facilitate the usage of Datacentertracesdatasets package from a command line interface"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
datacentertracesdatasets-cli = "datacentertracesdatasets_cli.cli:main"

[project.urls]
"Homepage" = "https://github.com/alejandrofdez-us/similarity-ts-cli"
"Bug Tracker" = "https://github.com/alejandrofdez-us/similarity-ts-cli/issues"