[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "quizapp"
version = "1.0.0"
authors = [
		{ name="Dylan Longert", email="longert520@gmail.com" },
		{ name="Somya Nagar", email="somyanagar49@gmail.com" }
	]
description = "A quiz app"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]
[project.urls]
Homepage = "https://github.com/somyanagar/quizapp_CI.git"